### ISSUE TITLE
[BUG]: Chalk dependency can't be fulfilled

### ISSUE THREAD

**Issue by garrettmflynn** [brainsatplay/tinybuild#1]
### Description of the bug

When installing `tinybuild` globally or locally from NPM, the .d.ts plugin requires the `chalk` library. But when you install this library, it doesn't let you import the library inside the bundle because of inconsistent ESM and CommonJS syntax.

Maybe we need to bundle chalk in the distribution?

### Steps To Reproduce

1. Open a new terminal
2. Install tinybuild using `npm i -g tinybuild`
3. Run `tinybuild`
4. Install chalk using `npm i -g tinybuild`
5. Repeat Step 2

**Comment by joshbrew** [comment]
Fixed, I just removed it, its only used to style console logs
